/** @type {import('cz-git').UserConfig} */
module.exports = {
  alias: { fd: 'docs: fix typos' },
  messages: {
    type: "Select the type of change you're committing:",
    scope: 'Select the scope of this change (optional):',
    customScope: 'Enter the custom scope:',
    subject: 'Write a short, imperative-tense description:\n',
    body: 'Provide a longer description (optional). Use "|" for a new line:\n',
    breaking: 'List any BREAKING CHANGES (optional):\n',
    footerPrefixesSelect: 'Select the issue references this commit affects (optional):',
    footerPrefixes: 'Enter the issue prefix (e.g. "Closes"):',
    footer: 'List issue references (optional). E.g.: #31, #34:\n',
    confirmCommit: 'Confirm the commit above?',
  },
  types: [
    { value: 'feat', name: 'feat:     A new feature' },
    { value: 'fix', name: 'fix:      A bug fix' },
    { value: 'docs', name: 'docs:     Documentation only changes' },
    { value: 'style', name: 'style:    Formatting, missing semicolons, etc (no code change)' },
    { value: 'refactor', name: 'refactor: Code change that neither fixes a bug nor adds a feature' },
    { value: 'perf', name: 'perf:     Code change that improves performance' },
    { value: 'test', name: 'test:     Adding or correcting tests' },
    { value: 'build', name: 'build:    Build system or external dependencies' },
    { value: 'ci', name: 'ci:       CI configuration/scripts' },
    { value: 'chore', name: 'chore:    Other changes that don\'t modify src or test files' },
    { value: 'revert', name: 'revert:   Reverts a previous commit' },
  ],
  scopes: [
    'events',
    'availability',
    'reservations',
    'core/entities',
    'core/database',
    'core/cache',
    'core/logging',
    'core/realtime',
    'deps',
  ],
  useEmoji: false,
  skipQuestions: ['footerPrefixesSelect', 'footerPrefixes'],
  minSubjectLength: 0,
  upperCaseSubject: false,
};
